name: 'Setup docker buildx'
description: 'Setup docker buildx'

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    # Install dependencies for QEMU and ARM
    - name: Install QEMU and ARM libraries
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static libc6-armhf

    # Release version setup
    - uses: ./.github/actions/get-release-version
